import Header from "@/components/Header";
import RelationDashBar from "@/components/RelationDashBar";
import RootSidebar from "@/components/RootSidebar";
import { RootTabLinks } from "@/constants/index.js";
import { ThemeProvider } from "@/context/ThemeProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-black">
        <div>
          <Header />

          <RelationDashBar />
        </div>
        <div className="flex container mx-auto">
          <div className="w-full dark:bg-black bg-white border max-w-[250px] h-screen">
            <RootSidebar items={RootTabLinks} />
          </div>
          <div className="w-full border">
            <ThemeProvider>{children}</ThemeProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
